# PRUEBAS CON NUMPY

- Operadores
- Funciones
- Ficheros

In [1]:
import numpy as np

In [2]:
datos = np.random.rand(2,5,3)
datos

array([[[0.89869321, 0.44739224, 0.46034606],
        [0.86656044, 0.88217555, 0.86188418],
        [0.45664691, 0.24550993, 0.71300193],
        [0.8212293 , 0.69244393, 0.68650451],
        [0.7960118 , 0.63843969, 0.39647412]],

       [[0.10125034, 0.06748559, 0.97644951],
        [0.66966249, 0.01282808, 0.74372581],
        [0.78950739, 0.45416995, 0.06251742],
        [0.95387279, 0.515998  , 0.94494539],
        [0.17260024, 0.38889219, 0.98856671]]])

In [3]:
type(datos)

numpy.ndarray

In [4]:
d = np.array([1,3,4,5])
d2 = np.array([12, 8.8, 5, 3.88])

In [5]:
d2

array([12.  ,  8.8 ,  5.  ,  3.88])

In [6]:
d3 = np.array(['12','6','9'], dtype=np.int8)
d3

array([12,  6,  9], dtype=int8)

In [7]:
d2 = d2.astype(np.int8)
d2

array([12,  8,  5,  3], dtype=int8)

In [8]:
d2.shape

(4,)

In [9]:
datos.shape

(2, 5, 3)

In [10]:
datos2 = np.zeros_like(datos)
datos2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
datos = datos * 10
datos = datos.astype(np.int16)
datos

array([[[8, 4, 4],
        [8, 8, 8],
        [4, 2, 7],
        [8, 6, 6],
        [7, 6, 3]],

       [[1, 0, 9],
        [6, 0, 7],
        [7, 4, 0],
        [9, 5, 9],
        [1, 3, 9]]], dtype=int16)

In [12]:
arr1 = np.random.randint(1,30,20)
arr1

array([25,  6,  8, 10, 25, 26,  4, 12, 21, 15, 12, 14,  2,  6, 12, 24, 14,
        2, 15,  3])

In [13]:
arr2 = np.random.randint(1,30,20)
arr2

array([15, 29,  2, 18,  1,  4, 18,  9,  4, 23, 15, 29, 14, 14,  2,  8, 25,
       27,  5, 27])

In [14]:
# Filtrar los números entre 15 y 25
arr1[(arr1 >= 15) & (arr1 <= 25 )]

array([25, 25, 21, 15, 24, 15])

In [15]:
arr1 > arr2

array([ True, False,  True, False,  True,  True, False,  True,  True,
       False, False, False, False, False,  True,  True, False, False,
        True, False])

In [16]:
suma = arr1 + arr2
suma

array([40, 35, 10, 28, 26, 30, 22, 21, 25, 38, 27, 43, 16, 20, 14, 32, 39,
       29, 20, 30])

In [17]:
arr2[arr2 >= 20] = 20
arr2

array([15, 20,  2, 18,  1,  4, 18,  9,  4, 20, 15, 20, 14, 14,  2,  8, 20,
       20,  5, 20])

In [18]:
m = np.eye(6)
m

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
m[1:-1,1:-1]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
m = np.arange(25).reshape(5,-1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
m[[0,3,4]]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
indices = np.array([True, False, False, True, True])
m[indices]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
a = m.T
a[0] = 0
b = a.T
b

array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0, 11, 12, 13, 14],
       [ 0, 16, 17, 18, 19],
       [ 0, 21, 22, 23, 24]])

In [25]:
def modificarCol(m, col, valor):
    a = m.T
    a[col] = valor
    b = a.T
    return b

In [26]:
m

array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0, 11, 12, 13, 14],
       [ 0, 16, 17, 18, 19],
       [ 0, 21, 22, 23, 24]])

In [27]:
m2 = modificarCol(m, 3, 10)
m2

array([[ 0,  1,  2, 10,  4],
       [ 0,  6,  7, 10,  9],
       [ 0, 11, 12, 10, 14],
       [ 0, 16, 17, 10, 19],
       [ 0, 21, 22, 10, 24]])

In [28]:
arr1 = np.random.randint(1,30,20)
arr1

array([28, 25,  9, 14, 14, 24,  4, 17, 17, 13, 23, 18, 26,  6, 13,  4,  2,
       22, 18,  5])

In [29]:
arr2 = np.random.randint(1,30,20)
arr2

array([ 6,  4, 20,  7,  1,  2, 27, 13,  9,  2, 21, 19, 24,  4,  7,  8, 20,
       12, 18, 11])

In [30]:
maximos = np.maximum(arr1, arr2)
maximos

array([28, 25, 20, 14, 14, 24, 27, 17, 17, 13, 23, 19, 26,  6, 13,  8, 20,
       22, 18, 11])

In [32]:
minimos = np.minimum(arr1, arr2)
minimos

array([ 6,  4,  9,  7,  1,  2,  4, 13,  9,  2, 21, 18, 24,  4,  7,  4,  2,
       12, 18,  5])

In [33]:
L1 = [2,4,5,6]
L2 = [5,6,1,0]
np.minimum(L1, L2)

array([2, 4, 1, 0])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
def identidad(n=5):
    arr = np.arange(1,n+1)    
    m = np.eye(n)    
    m2 = np.where(m!=0,arr,0)
    return m2

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [ ]:
idetni