## ENTRADA SALIDA CON NUMPY

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,50,30).reshape(6,5)
a

array([[15, 38, 25, 33,  5],
       [44, 16, 13, 30,  3],
       [27, 27, 46, 17, 27],
       [25, 29,  9, 19, 10],
       [25, 19, 43, 36,  2],
       [34, 26, 45,  2, 19]])

In [3]:
b = np.random.randint(1,50,30).reshape(6,5)
b

array([[18,  6, 40, 45, 12],
       [19, 12,  1, 12, 35],
       [ 6, 27, 12, 42, 48],
       [29,  4, 34, 38,  5],
       [14, 24,  3, 38,  2],
       [ 6, 42, 22, 22, 42]])

Ficheros binarios

In [8]:
np.save('matriz', a)

In [9]:
a2 = np.load('matriz.npy')

In [10]:
a2

array([[15, 38, 25, 33,  5],
       [44, 16, 13, 30,  3],
       [27, 27, 46, 17, 27],
       [25, 29,  9, 19, 10],
       [25, 19, 43, 36,  2],
       [34, 26, 45,  2, 19]])